### ISSUE TITLE
about periodicity artifacts

### ISSUE THREAD

**Issue by hdmjdp** [mindslab-ai/phaseaug#6]
what is periodicity artifacts? can you show me the mel-image?

**Comment by junjun3518** [comment]
Hi @hdmjdp!

We get a concept from [CARGAN](https://www.maxrmorrison.com/sites/cargan/).
Periodity artifacts are kind of failed reconstruction of periodicity, so we can hear it by tik sound or brief silence.

Periodity artifacts are occured at very short moment, so hard to observe by mel spectrogram.
I will give you a example with raw audio images.

This image is raw audio plot by audacity, and you will find weird signal between 2.44s~2.5s for HiFiGAN without PhaseAug.
<img width="1084" alt="스크린샷 2022-12-08 오후 5 29 51" src="https://user-images.githubusercontent.com/36876966/206398407-a8e9b494-57a9-421a-9095-b95e5e0b125a.png">

It is a first sample of a [demo page](https://mindslab-ai.github.io/phaseaug/)'s HiFiGAN section, and you can hear more speechs.
Our method could not remove all artifacts, but it reduce occurrence in evaluation.

Thank you for your interest!
Best regards,
Junhyeok Lee

**Comment by hdmjdp** [comment]
thanks!
