### ISSUE TITLE
Changed in version 2.0: Real datatype inputs are no longer supported.

### ISSUE THREAD

**Issue by Aloento** [mindslab-ai/phaseaug#8]
https://pytorch.org/docs/stable/generated/torch.istft.html#:~:text=datatype%20inputs%20are-,no%20longer%20supported,-.%20Input%20must%20now

in `PhaseAug` -> `forward9(_sync)`

`x_aug = torch.istft(`

> RuntimeError: istft requires a complex-valued input tensor matching the output from stft with return_complex=True.

Maybe:

`X_aug = X * torch.complex(phi.cos(), -phi.sin())`

**Comment by junjun3518** [comment]
Yes, I plan to update it in the near future as mentioned in my todo list: `PyTorch 2.0 is released, need to modify STFT and iSTFT for complex support`.

However, it will take some time since I only have machines with older versions of drivers.

**Comment by junjun3518** [comment]
Updated! Now phaseaug==1.0.0 is available for both pytorch>=2.0.0 and pytorch>=1.7.0
